Hotfix/marketing hero
fntechgit/virtualevent-poc pull request #100
Opened 2021-09-10 03:50 UTC by tomrndom

**What kind of change does this PR introduce?**

* Fix checking image quantity for use of slider
* Adjusting slider height dynamically

**Does this PR introduce a breaking change?**

None

**What needs to be documented once your changes are merged?**

None

2021-09-13 13:44 UTC, smarcet commented on src/components/MarketingHeroComponent.js
> +                    <div className={styles.imageSlider} style={{ backgroundImage: `url(${img.image})`, height: sliderHeight, marginBottom: -6 }} />
originally sliderHeight is null is that correct ?

2021-09-13 16:36 UTC, tomrndom commented on src/components/MarketingHeroComponent.js
> +                    <div className={styles.imageSlider} style={{ backgroundImage: `url(${img.image})`, height: sliderHeight, marginBottom: -6 }} />
I'll set a default value using the old hardcoded value

2021-09-23 15:55 UTC, smarcet requested changes
@tomrndom please review comments

2021-09-27 14:13 UTC, smarcet approved these changes
looks good to me

2021-09-27 14:13 UTC, merged