Fixed DataSync issue
fntechgit/virtualevent-poc pull request #299
Opened 2022-03-02 23:34 UTC by smarcet

* clearing the clock and clearing the current event on data synch action leaded
  to a white screen error

Signed-off-by: smarcet <smarcet@gmail.com>

ref https://tipit.avaza.com/project/view/295592#!tab=task-pane&task=2846562

2022-03-03 19:23 UTC, smarcet commented
@gcutrini @santipalenque @JpMaxMan @romanetar please review this is very important to prevent white screen bugs
regards

2022-03-03 19:37 UTC, gcutrini reviewed
looks good to me

2022-03-03 21:37 UTC, santipalenque requested changes

2022-03-03 21:37 UTC, santipalenque commented on src/actions/schedule-actions.js
> +export const RELOAD_SCHED_DATA = 'RELOAD_SCHED_DATA';
why did you create these two actions that do the same as SYNC_DATA and GET_USER_PROFILE ?

2022-03-03 21:37 UTC, santipalenque commented on src/actions/schedule-actions.js
> +    dispatch(createAction(RELOAD_USER_PROFILE)({isLoggedUser, userProfile }));
this action call here doesnt make any sense since schedules is empty

2022-03-03 21:37 UTC, santipalenque commented on src/reducers/all-schedules-reducer.js
> +            const {userProfile} = payload?.response ?? payload;
can you consolidate the payload instead of this ?

2022-03-04 01:18 UTC, smarcet commented on src/actions/schedule-actions.js
> +export const RELOAD_SCHED_DATA = 'RELOAD_SCHED_DATA';
Bc i don't need to trigger synch data just need to trigger schedule reload

2022-03-04 01:18 UTC, smarcet commented on src/actions/schedule-actions.js
> +    dispatch(createAction(RELOAD_USER_PROFILE)({isLoggedUser, userProfile }));
That reload the schedule after a page hard refresh

2022-03-04 01:19 UTC, smarcet commented on src/reducers/all-schedules-reducer.js
> +            const {userProfile} = payload?.response ?? payload;
No bc one is came from an API call and another from a raw action

2022-03-04 12:54 UTC, santipalenque approved these changes

2022-03-04 14:15 UTC, merged