Updated strategy to retrieve activity data on activity detail page
fntechgit/virtualevent-poc pull request #305
Opened 2022-03-03 20:41 UTC by smarcet

* now first its provided the data on the reducer and in background is
  retrieved fresh data from api

Signed-off-by: smarcet <smarcet@gmail.com>

ref 

https://tipit.avaza.com/project/view/295592#!tab=task-pane&task=2837819

2022-03-03 21:54 UTC, santipalenque requested changes

2022-03-03 21:54 UTC, santipalenque commented on src/routes/WithBadgeRoute.js
> +  const needsToLoadEvent = parseInt(eventId) && parseInt(eventId) !== parseInt(event?.id);
I think this change is not necessary, its already comparing two strings

2022-03-03 21:54 UTC, santipalenque commented on src/routes/WithBadgeRoute.js
> +    if (event === null || parseInt(eventId) !== parseInt(event?.id)) {
no need to check event twice

2022-03-04 01:37 UTC, smarcet commented on src/routes/WithBadgeRoute.js
> +  const needsToLoadEvent = parseInt(eventId) && parseInt(eventId) !== parseInt(event?.id);
no wrong , one is an string and the other is a an int

2022-03-04 01:50 UTC, merged