Feature/a11y home sections semantics
fntechgit/virtualevent-poc pull request #341
Opened 2022-03-09 18:00 UTC by camilokawerin

**What's broken**

Every section in a page must be marked with proper sectioning tag and must be labelled by a heading or `aria-label` attribute. This allows user with assistive technologies to navigate the page searching for landmarks in it.

**What kind of change does this PR introduce?**

Added sectioning tags and attributes where it is necessary.

2022-03-10 11:32 UTC, mrazzari commented on src/components/LobbyHeroComponent.js
> +            <p className="subtitle" role="doc-subtitle">
Skip `role="doc-subtitle"`. It adds unnecesary levels to heading navigation. [Always trust Adrian](https://adrianroselli.com/2020/08/be-wary-of-doc-subtitle.html#Verdict).

2022-03-10 11:39 UTC, mrazzari requested changes
Minor change requested.

2022-03-10 22:06 UTC, mrazzari commented on src/components/LobbyHeroComponent.js
> +  <header className="hero">
Let's go back to section.  (Avoid nesting header within main. Doesn't create a landmark, and if it did, wouldn't be valuable for users.)

2022-03-10 22:06 UTC, mrazzari requested changes
Minor change requested.

2022-03-11 10:58 UTC, camilokawerin commented on src/components/LobbyHeroComponent.js
> +  <header className="hero">
Then let's go to DIV, so it doesn't create a landmark at all. In fact, this is just a visual container for H1.

2022-03-14 19:30 UTC, mrazzari reviewed
LGTM

2022-03-14 19:30 UTC, mrazzari approved these changes

2022-03-24 16:58 UTC, smarcet commented
@camilokawerin could you please fix the merge conflicts ?
much thanks!

2022-03-25 12:16 UTC, camilokawerin commented
@smarcet done!

2022-03-25 19:39 UTC, gcutrini approved these changes

2022-03-28 13:48 UTC, merged