Feature/a11y header landmarks
fntechgit/virtualevent-poc pull request #343
Opened 2022-03-10 13:00 UTC by camilokawerin

It's better for screen readers to separate banner landmark from navigation landmark. Also 'Main navigation' as label is redundant.

**What kind of change does this PR introduce?**

Markup changes in Header and Navbar components.

**Does this PR introduce a breaking change?**

No.

**What needs to be documented once your changes are merged?**

No.

2022-03-10 22:12 UTC, mrazzari approved these changes
Good call on these changes.

2022-03-11 13:48 UTC, mrazzari approved these changes

2022-03-14 18:43 UTC, mrazzari requested changes
@camilokawerin I've been discussing with @gcutrini, he suggested refactoring this into 1 single "Navbar.js" module. 

Rationale:
* Header only contains the logo and the button to open the navbar (hence it's part of Navbar even if not inside `<nav>`.
* Minimize git history diff by editing Navbar (the bigger file) and deleting Header.js.
(This also means fixing references to Header)

2022-03-15 13:18 UTC, mrazzari approved these changes

2022-03-23 17:25 UTC, camilokawerin commented
> do we still need this logo property ?

No, we don't. I've removed it.

2022-03-25 19:35 UTC, gcutrini approved these changes

2022-03-28 13:48 UTC, merged