Feature/disqus shortname env var
fntechgit/virtualevent-poc pull request #349
Opened 2022-03-16 18:39 UTC by gcutrini

Ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2599375&fileview=grid

2022-03-16 18:41 UTC, gcutrini commented
This will require adding GATSBY_DISQUS_SHORTNAME var in local .env and on new Netlify deploys.

2022-03-17 15:33 UTC, smarcet commented on src/components/DisqusComponent.js
> +          shortname={getEnvVariable(DISQUS_SHORTNAME)}
could we define a default value ?

2022-03-17 15:34 UTC, smarcet requested changes
@gcutrini please review comments
much thanks

2022-04-07 18:15 UTC, smarcet approved these changes
LGTM

2022-04-07 18:15 UTC, merged