Registration Lite implementation
fntechgit/virtualevent-poc pull request #65
Opened 2021-07-20 22:48 UTC by tomrndom

Implementation of registration-lite-widget into schedule-revamp branch

2021-07-21 14:32 UTC, santipalenque requested changes
hey Tom, please check my comments and let me know if you have any questions

2021-07-21 14:32 UTC, santipalenque commented on src/components/RegistrationLiteComponent.js
> +                switch (p) {
this section can improve,  create an array with the constants for each provider and add a key, for example :
[ {key: facebook, color: '#0370C5', label: 'Facebook'}, ...] = providers
then filter that array with the keys in providers_array like this :
activeProviders = providers.filter(p => providers_array.includes(p.key))

2021-07-21 14:32 UTC, santipalenque commented on src/routes/PrivateRoute.js
> +  if (hasTicket === true && isAuthorized === false && requireExtraQuestions(userProfile) && location.pathname === "/a/extra-questions") {
unify all if conditions please

2021-07-21 14:32 UTC, santipalenque commented on src/routes/PrivateRoute.js
> +  if (hasTicket === true && isAuthorized === false && requireExtraQuestions(userProfile) && location.pathname !== "/a/extra-questions") {
this is almost the same if as the previous one

2021-07-21 14:32 UTC, santipalenque commented on src/routes/PrivateRoute.js
> +  if (isAuthorized === false && hasTicket === false && location.pathname !== "/a/extra-questions") {
and also this one

2021-07-21 14:32 UTC, santipalenque commented on src/pages/a.js
> +          <PrivateRoute path="/extra-questions" summit_phase={summit_phase} component={extraQuestionsPage} isLoggedIn={isLoggedUser} user={user} location={location} />
remove all unnecessary props

2021-07-21 14:32 UTC, santipalenque commented on src/templates/extra-questions-page.js
> +import withOrchestra from "../utils/widgetOrchestra";
we don't need this anymore, remove please

2021-07-21 14:32 UTC, santipalenque commented on src/templates/extra-questions-page.js
> +import SummitObject from '../content/summit.json';
use reducer instead

2021-07-21 14:32 UTC, santipalenque commented on src/templates/extra-questions-page.js
> +    useState(() => {
not sure what you did here, was this supposed to be useEffect ?

2021-07-21 14:32 UTC, santipalenque commented on src/templates/extra-questions-page.js
> +    const mandatoryQuestions = () => {
this should be named mandatoryQuestionsAnswered

2021-07-21 14:32 UTC, santipalenque commented on src/templates/extra-questions-page.js
> +            return disclaimer && mandatoryAnswers;
using the disclaimer here can lead to a race condition bug, we need to rethink this

2021-07-21 14:32 UTC, santipalenque commented on src/templates/extra-questions-page.js
> +    const handleDisclaimer = () => setDisclaimer(!disclaimer);
this should be named toggleDisclaimer

2021-07-21 14:32 UTC, santipalenque commented on src/templates/extra-questions-page.js
> +    const getInput = (question) => {
move all this to a separate functional component

2021-07-21 14:32 UTC, santipalenque commented on src/templates/extra-questions-page.js
> +        <React.Fragment>
use <> instead

2021-07-21 14:32 UTC, santipalenque commented on src/templates/extra-questions-page.js
> +                        {answers.length === extraQuestions.length && extraQuestions.map(question => {
this can be written like this extraQuestions.map(getInput)

2021-07-21 14:32 UTC, santipalenque commented on src/templates/extra-questions-page.js
> +const OrchestedTemplate = withOrchestra(ExtraQuestionsPageTemplate);
no need for Orchestra

2021-07-21 14:32 UTC, santipalenque commented on src/utils/fragmentParser.js
> +import { FragmentParser } from "openstack-uicore-foundation/lib/components";
I thnk we can jsut use the uicore fragmentParser

2021-07-21 14:32 UTC, santipalenque commented on src/utils/userUtils.js
> +                if (answer && answer.value) {
makes no sense ,just return (answer && anwer.value)

2021-07-21 14:50 UTC, smarcet commented on src/utils/withAccessToken.js
> +import React, { useEffect, useState } from 'react';
this HOC was a work around
every time that some action needs an access token needs to invoque
import { getAccessToken } from 'openstack-uicore-foundation/lib/methods';
directly also the reference to this method could be passed using https://github.com/reduxjs/redux-thunk like this

Since 2.1.0, Redux Thunk supports injecting a custom argument using the withExtraArgument function:

import { getAccessToken } from 'openstack-uicore-foundation/lib/methods';

const store = createStore(
reducer,
applyMiddleware(thunk.withExtraArgument(getAccessToken)),
);

// later
export const getUser = (id ) => async (dispatch, getState, getAccessToken) => {

const accessToken = await getAccessToken();
}

2021-07-23 14:04 UTC, smarcet commented on src/templates/extra-questions-page.js
> +        const userAnswers = user.summit_tickets[0].owner.extra_questions;
@tomrndom former comment from @santipalenque could be resolved if u assign as initial state the calculations that you are already performing on the useEffect hook
like this
const [disclaimer, setDisclaimer] = useState(user.summit_tickets[0].owner.disclaimer_accepted);

matter of fact all the set of the initial state on the useEffect could be moved to the initial state

2021-07-23 14:21 UTC, smarcet commented on src/utils/userUtils.js
> +export const requireExtraQuestions = (profile) => {
Summit should be passed by param and use the state of the global reducer

2021-07-23 14:23 UTC, smarcet commented on src/routes/authorization-callback-route.js
> +    this.props.getUserProfile();
here i do think that will be better to chain actions using then
this.props.getIDPProfile().then(() => this.props.getUserProfile())

2021-07-23 14:31 UTC, santipalenque requested changes

2021-07-23 14:31 UTC, santipalenque commented on src/routes/PrivateRoute.js
>    if (loading || userProfile === null || hasTicket === null || isAuthorized === null || userRevalidation === null ||
avoid this long if conditions. move this to a method isUserReady() or similar

2021-07-23 14:31 UTC, santipalenque commented on src/utils/userUtils.js
> +import SummitObject from '../content/summit.json';
use State , we will only use the reducer as the data source from now on, the only place where we will include any .json file will be in the reducer

2021-07-23 14:37 UTC, smarcet requested changes
@tomrndom please review comments

2021-07-23 14:42 UTC, santipalenque commented on src/utils/userUtils.js
> +import SummitObject from '../content/summit.json';
if you use getState and pass this method through connect, then you should move the method to one of the actions files, maybe user-actions. If you choose to pass the summit  order_extra_questions as param, then leave it here

2021-07-23 15:01 UTC, santipalenque commented on src/routes/PrivateRoute.js
>    if (loading || userProfile === null || hasTicket === null || isAuthorized === null || userRevalidation === null ||
checkout this operator: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

2021-07-27 03:16 UTC, smarcet approved these changes
these looks good to me
approved

2021-07-27 03:20 UTC, merged