use full schedule for my schedule
fntechgit/virtualevent-poc pull request #83
Opened 2021-09-01 13:47 UTC by santipalenque

**What kind of change does this PR introduce?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

2021-09-03 14:35 UTC, smarcet commented on src/pages/a.js
> +          <PrivateRoute path="/my-schedule" component={MySchedulePage} location={location} summit_phase={summit_phase} isLoggedIn={isLoggedUser} user={user}/>
my schedule should be a private route
check this slack conversation https://tipit.slack.com/archives/C01093753J8/p1629764390084100?thread_ts=1629744124.081000&cid=C01093753J8
if u use a private route instead of a public one
its display the is not show time meassage and kick u out
users should be able to access my-schedule page before shows happens

2021-09-03 14:37 UTC, smarcet commented on src/templates/my-schedule-page.js
>    if (isLoggedUser && summitPhase !== PHASES.BEFORE) {
this condition is preventing users to add to my schedule before summits ? if so users should be able to add to my schedule before summit

2021-09-03 14:40 UTC, smarcet requested changes
please review comments 
regards

2021-09-03 18:19 UTC, santipalenque commented on src/pages/a.js
> +          <PrivateRoute path="/my-schedule" component={MySchedulePage} location={location} summit_phase={summit_phase} isLoggedIn={isLoggedUser} user={user}/>
this routing issue will be handled separately

2021-09-07 13:27 UTC, smarcet approved these changes
looks good to me

2021-09-07 14:36 UTC, merged