Refactor Routes
fntechgit/virtualevent-poc pull request #91
Opened 2021-09-03 18:32 UTC by santipalenque

refactoring of routes logic so we use the lib as we should and it makes sense

2021-09-06 17:26 UTC, smarcet commented on src/routes/WithAuthRoute.js
> +    return (<HeroComponent title="You are not authorized to view this session!" />);
this is not correct
please check https://github.com/fntechgit/virtualevent-poc/blob/87c6ab97843770daba94ce29129ff6f8fd7f6d22/src/routes/PrivateRoute.js#L77
we need to redirect to page https://github.com/fntechgit/virtualevent-poc/blob/main/src/pages/authz/ticket.js to continue with the redirection flow to registration

2021-09-06 17:26 UTC, smarcet requested changes
please review comments and remove *.json files
regards

2021-09-06 21:59 UTC, santipalenque commented on src/routes/WithAuthRoute.js
> +    return (<HeroComponent title="You are not authorized to view this session!" />);
got it, added redirect back in . Removed withTicket route since it is covered inside withAuth

2021-09-06 22:06 UTC, santipalenque commented
done @smarcet please check again

2021-09-07 18:01 UTC, smarcet approved these changes
looks good to me

2021-09-07 18:01 UTC, merged